#!/usr/bin/env bash
# @file skdiff.sh
# Show artboard changes between two Sketch files
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>

[[ "$OSTYPE" == "darwin"* ]] || {
    echo "This will only run on macOS"
    exit 1
}

[[ -e /Applications/Sketch.app/Contents/Resources/sketchtool/bin/sketchtool ]] || {
    echo "Unable to find sketchtool under your Sketch application directory"
    exit 1
}
sketch=/Applications/Sketch.app/Contents/Resources/sketchtool/bin/sketchtool

type blink-diff &> /dev/null || {
    type npm &> /dev/null || {
        echo "To run image difference detection you need to install blink-diff"
        echo "using the node package manager (npm). Please install npm."
        echo "Instructions at https://www.npmjs.com/get-npm"
        exit 1
    }
    echo "Installing blink-diff..."
    npm install -g blink-diff
    echo
}

QUIET=no
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
RESULTS_DIR='changes'
WORKING_DIR=~/.skdiff
FILE_A=''
FILE_B=''
NUM_DIFFS=0
DIFF_VERSION='no'

[[ ! -L /usr/local/bin/skdiff ]] && ln -sf "$SCRIPTPATH/skdiff" /usr/local/bin

[[ "$0" = "$BASH_SOURCE" ]] && SOURCED='no' || SOURCED='yes';

_help() {
    echo "Show visual differences between Sketch files."
    echo "Artbards added, deleted and visual changes are generated"
    echo "Usage: "
    echo "  skdiff FILE_A.sketch FILE_B.sketch [options]"
    echo "  skdiff FILE_A.sketch [options]"
    echo "When involed with one Sketch file, it is assumed the file exists"
    echo "within a git repository and will be diff'ed against a previous"
    echi "version."
    echo "Options:"
    echo "  -h, --help, help ... display this help information"
    echo "  -q, --quiet ........ supress progress messages"
    echo "  -o, --output ....... the directory for generated images"
    echo "                       Defaults to directory name: $RESULTS_DIR"
    return 0
}

err()   { echo -e "\e[0;31m${@}\e[0m" 1>&2; }
msg()   { [[ "$QUIET" == 'no' ]] && echo -en "\e[0;37m${@}\e[0m"; }

fileExists() {
    [[ ! -f "$1" ]] && {
        err "Unable to find file, $1"
        return 1
    }
    [[ "$1" != *.sketch ]] && {
        err "The file, $1, does not appear to be a sketch file"
        return 1
    }
    return 0
}

exportSketchArtboards () {
    # - export the artboards from a Sketch file
    # - reduce all artboard PNG filepaths to a file
    # - cache resulting artboards in a working dir
    # @param location of the Sketch file
    # @param (optionai) [yes|no] clearing any cached artboard export
    #        default to yes

    local filepath="$1"
    local filename=$(basename "$1")
    local clearCache="${2:-yes}"

    fileExists "$filepath" || exit 1

    local dir="$WORKING_DIR/${filename%.sketch}_artboards"
    if [[ -d "$dir" && "$clearCache" != 'yes' ]]; then return 0; fi
    [[ -d "$dir" ]] && rm -fR "$dir"

    ## TODO: Add option to export symbols too
    "$sketch" export artboards "$filepath" \
        --overwriting="YES" \
        --include-symbols="NO" \
        --output="$dir" > /dev/null

    while IFS= read -r _filename; do
        _file="${_filename#*/}" # strip containing dir
        _file="${_file// /_}"   # underscore all spaces
        _file="${_file//\//_}"  # underscore directory delimitor
        mv "$WORKING_DIR/$_filename" "$dir/$_file"
    done < <(find "$dir" -name "*.png" | sed -En "s#${WORKING_DIR}/##p")

    find "$dir" -type d -empty -delete

    return 0
}

diffSketchArtboards () {
    # - diff two directories of exported Sketch artboards
    # - echo summary
    # - generate directory of added, removed and changes artboard images
    # @param name of first Sketch file
    # @param name of second Sketch file
    # @param (optional) output directory path

    local pathnameA="$1"
    local dirnameA=$(basename "$pathnameA")
    local pathnameB="$2"
    local dirnameB=$(basename "$pathnameB")
    local odir="${3:-$RESULTS_DIR}"

    [ -d "$odir" ] && rm -fR "$odir"
    mkdir -p  "$odir/changed" "$odir/added" "$odir/deleted"

    while IFS= read -r _line; do
        _differ=$(echo "$_line" | sed -En 's#^Files (.*) and (.*) differ$#\1#p')
        _added=$(echo "$_line" | sed -En "s#^Only in .*${dirnameB}: (.*\.png)\$#\1#p")
        _removed=$(echo "$_line" | sed -En "s#^Only in .*${dirnameA}: (.*\.png)\$#\1#p")
        if [[ ! -z "$_differ" ]]; then
            _file=$(basename "$_differ")
            blink-diff --compose-ltr --output "$odir/changed/$_file" \
                "$WORKING_DIR/$dirnameA/$_file" \
                "$WORKING_DIR/$dirnameB/$_file" >/dev/null
            msg "\e[0;33m<> $_file has changed\n"
            (( NUM_DIFFS++ ))
        elif [[ ! -z "$_added" ]]; then
            cp "$WORKING_DIR/$dirnameB/$_added" "$odir/added/$_added"
            msg "\e[0;32m++ $_added added\n"
            (( NUM_DIFFS++ ))
        elif [[ ! -z "$_removed" ]]; then
            cp "$WORKING_DIR/$dirnameA/$_removed" "$odir/deleted/$_removed"
            msg "\e[0;31m-- $_removed removed\n"
            (( NUM_DIFFS++ ))
        fi
    done < <(diff -rq "$WORKING_DIR/$dirnameA" "$WORKING_DIR/$dirnameB" | grep .png)

    return 0
}

genGitHook () {
    # WORK IN PROGRESS
    # generate a git post-commit hook to export artboards from any Sketch
    # files in the commit

    local git_root
    git_root=$(git rev-parse --show-toplevel)
    [[ -e "$git_root" ]] || {
        echo "You don't appear to be in a git repository"
        exit 1
    }
    _hookFile="$git_root/.git/hooks/post-commit"

    [[ -e "$_hookFile" ]] || {
        echo "\
#!/usr/bin/env
# @file post-commit githook
# Export artboards for any sketch files commited
# Generate directory of images showing differences between HEAD and last
# sketch file version
# (Generated by skdiff)
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>

"
    }

    echo "\
set -e 

# Diagnostic info
#echo \"Running \$BASH_SOURCE\"
#echo \"PWD is \$PWD\"
#echo -e \"Git environment vars:\\n\$(set | egrep GIT)\"

source \"$SCRIPTPATH/../skdiff.sh\"

# Export sketch artboards for any Sketch files added/changed in this commit
thisCommitSha=\"\$(git log -1 | grep -e '^commit' | awk '{print \$2}')\"
thisCommitFiles=\"\$(git log -1 --name-status | grep .sketch | egrep -v '^D' | awk '{print \$2}')\"
for file in \$thisCommitFiles; do
    exportSketchArtboards \"\$file\"
    exportDir=\"\${file%.sketch}_artboards\"
    commitDir=\"\$(dirname \$file)/.\$thisCommitSha/\$file\"
    mkdir -p \"\$commitDir\"
    mv \"\$exportDir\"/* \"\$commitDir\"
done
"
    return 0
}

[[ "$SOURCED" == 'yes' ]] && return 0

[[ $# == 0 ]] && { _help; exit 1; }
while [[ $# -gt 0 ]]; do
    arg="$1"
    case $arg in
        -o|--output)    RESULTS_DIR=$2; shift;;
        -q|--quiet)     QUIET=yes; shift;;
        -d)             set -x;;
        -h|--help|help) _help; exit 1;;
        *)  # positional args
            if [ -z "$FILE_A" ]; then FILE_A=$1;
            elif [ -z "$FILE_B" ]; then FILE_B=$1;fi
            ;;
    esac
    shift
done

fileExists "$FILE_A" && ! fileExists "$FILE_B" 2>/dev/null && {
    ## TODO: Check file in git repo
    repoDir=$(git rev-parse --show-toplevel)
    ## TODO: Guard against not finding any previous version
    sha="$(git log -1 --follow "$FILE_A" | grep -e '^commit' | awk '{print $2}')"
    currentVersion=$(basename "$FILE_A")
    lastVersion=".${currentVersion%.sketch}-${sha}.sketch"
    fileRelative=$(find "$repoDir" -name "$currentVersion" | sed -e "s#${repoDir}/##g")
    git show "$sha":"$fileRelative" > "$lastVersion"
    FILE_B="$FILE_A"
    FILE_A="$lastVersion"
    DIFF_VERSION='yes'
}

fileExists "$FILE_A" && fileExists "$FILE_B" && {

    msg "Exporting artboards ..."
    exportSketchArtboards "$FILE_A" $([[ "$DIFF_VERSION" == 'yes' ]] && echo 'no')
    exportSketchArtboards "$FILE_B"

    msg " done\nLooking for differences...\n"
    diffSketchArtboards "$WORKING_DIR/${FILE_A%.sketch}_artboards" \
        "$WORKING_DIR/${FILE_B%.sketch}_artboards" \
        "$RESULTS_DIR"
        
    rm -f .*.sketch > /dev/null
    if [[ "$NUM_DIFFS" -gt 0 ]]; then
        msg "$NUM_DIFFS differences found and stored in directory, '$RESULTS_DIR'\n"
    else
        rm -fR "$RESULTS_DIR"
        msg "No differences found\n"
        exit 1
    fi
}

exit 0